name: "deploy vim help to gh-pages"
on:
  push:
    branches:
      - master
jobs:
  ghpages:
    name: Convert and deploy vim help
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: generate html
        uses: tsuyoshicho/action-vimhelp-html-generate@v1.2.1
        env:
          FOLDER: build
      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
